script: |
            # 1. Заходим в папку
            cd /home/ubuntu/spotify-diploma
            
            # --- НОВАЯ ЧАСТЬ: Авто-создание .env файла ---
            # Мы удаляем старый .env и пишем новый из секретов GitHub
            # Это гарантирует, что на сервере всегда актуальные пароли
            rm -f .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "MINIO_root_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}" >> .env
            # (Добавь сюда остальные переменные, если они есть в Secrets)
            # ---------------------------------------------

            # 2. Скачиваем код
            git pull origin main
            
            # 3. Запускаем
            docker compose up -d --build --remove-orphans
            
            # 4. Чистим мусор (удаляем старые ненужные образы, чтобы не забить диск)
            docker image prune -f
